### ISSUE TITLE
Is there a way to use this WITHOUT the create-react-app-buildpack

### ISSUE THREAD

**Issue by bobber205** [mars/heroku-js-runtime-env#6]
I'd love to use this standalone but I'm not sure how. Do you have any examples you could point me to?

"Just using" the build pack isn't an option for me at the moment.

**Comment by mars** [comment]
Thanks for voicing your request. I’m going to look into extracting the create-react-app-buildpack part of this into its own buildpack, so that it’s reusable for other situations. I’ll follow up soon (probably within a day) with status/progress/outcome.

**Comment by mars** [comment]
Here's a working generalization of the buildpack part of this:
https://github.com/mars/heroku-js-runtime-env-buildpack

I built & tested this new buildpack with Vue, because it's not React and I've never used Vue! Unfortunately, Vue's local dev mode does not pass `process.env` through to the serving Node process, so runtimeEnv() in dev mode is always empty 😞 It does work in production as a Heroku app 😁

Please open new issues/PRs there for the generalized use of this module.

**Comment by bobber205** [comment]
You are a hero my man! :D
